import { expect, test } from "@playwright/test";

// "ceylon-crafts" (backend/tests/e2e_server.py): verified, contact confirmed, one confirmed
// Instagram account, a returns policy, two unverified active products, no orders yet, and seeded
// history (72 → 66). The engine computes the current score: 0.40·80 + 0.25·50 + 0.35·50 = 62.

test("store page shows the trust summary and links to the passport", async ({ page }) => {
  await page.goto("/en/stores/ceylon-crafts");
  await expect(page.getByText("Overall trust score")).toBeVisible();
  await expect(page.getByRole("meter", { name: "Business trust" })).toHaveAttribute("aria-valuenow", "80");
  await page.getByRole("link", { name: "View Digital Trust Passport" }).click();
  await expect(page).toHaveURL(/\/en\/stores\/ceylon-crafts\/passport$/);
});

test("passport explains the score with sourced signals", async ({ page }) => {
  await page.goto("/en/stores/ceylon-crafts/passport");
  await expect(page.getByRole("heading", { level: 1, name: "Digital Trust Passport" })).toBeVisible();
  await expect(page.getByText("62", { exact: true }).first()).toBeVisible(); // the hero figure
  await expect(page.getByText("Developing").first()).toBeVisible();

  await expect(page.getByRole("heading", { name: "Why should I trust this business?" })).toBeVisible();
  const verified = page.getByRole("listitem").filter({ hasText: "Business registration verified by Trustora" });
  await expect(verified.getByText("Verified fact")).toBeVisible();
  await expect(verified.getByText("+40 points")).toBeVisible();
  // Seller statements are labelled as such, never as facts.
  const policies = page.getByRole("listitem").filter({ hasText: "Published policies: Returns" });
  await expect(policies.getByText("Seller-provided")).toBeVisible();
  await expect(page.getByText(/Limited transaction history on Trustora/)).toBeVisible();

  // Methodology and no-guarantee wording.
  await expect(page.getByText(/not generated by AI and are not a guarantee/)).toBeVisible();
});

test("passport shows the 30-day trust change with an accessible table", async ({ page }) => {
  await page.goto("/en/stores/ceylon-crafts/passport");
  await expect(page.getByText("Trust score decreased from 72 to 62 during the last 30 days.").first()).toBeVisible();
  await expect(page.getByRole("img", { name: /Line chart of the trust score over time/ })).toBeVisible();
  await page.getByText("Show as table").click();
  const rows = page.locator("details table tbody tr");
  await expect(rows).toHaveCount(3); // seeded change (20 days ago), engine computation, current
  await expect(rows.last()).toContainText("62");
});

test("passport is available in Sinhala", async ({ page }) => {
  await page.goto("/si/stores/ceylon-crafts/passport");
  await expect(page.getByRole("heading", { level: 1, name: "ඩිජිටල් Trust Passport" })).toBeVisible();
  await expect(page.getByText("ව්‍යාපාර ලියාපදිංචිය Trustora මගින් තහවුරු කර ඇත")).toBeVisible();
  await expect(page.getByText("තහවුරු කළ කරුණ").first()).toBeVisible();
  await expect(page.getByText("මම මෙම ව්‍යාපාරය විශ්වාස කළ යුත්තේ ඇයි?")).toBeVisible();
});

test("unpublished store has no public passport", async ({ page }) => {
  const response = await page.goto("/en/stores/draft-store/passport");
  expect(response?.status()).toBe(404);
});

test("trust management pages require sign-in", async ({ page }) => {
  await page.goto("/en/sme/passport");
  await expect(page).toHaveURL(/\/login\?next=%2Fen%2Fsme%2Fpassport$/);
  await page.goto("/en/admin/evidence");
  await expect(page).toHaveURL(/\/login\?next=%2Fen%2Fadmin%2Fevidence$/);
});

test("passport shows a rules-based summary when AI is not configured", async ({ page }) => {
  await page.goto("/en/stores/ceylon-crafts/passport");
  await expect(page.getByRole("heading", { level: 2, name: "Summary", exact: true })).toBeVisible();
  await expect(page.getByText(/^Based on the available evidence, .+ \(62\/100\)/)).toBeVisible();
  await expect(page.getByText("Generated from the signals on this page.")).toBeVisible();
  await expect(page.getByText("AI summary")).toHaveCount(0);
});

test("rules-based summary is written in Sinhala on /si", async ({ page }) => {
  await page.goto("/si/stores/ceylon-crafts/passport");
  await expect(page.getByRole("heading", { level: 2, name: "සාරාංශය", exact: true })).toBeVisible();
  await expect(page.getByText(/පවතින සාක්ෂි මත පදනම්ව/)).toBeVisible();
  await expect(page.getByText(/පවතින සාක්ෂි මත පදනම්ව/)).toHaveAttribute("lang", "si");
});
