"""Upload validation.

* File type is decided by the file's content (magic bytes), never by the client's
  Content-Type header or filename.
* The filename's extension must still match the detected type (rejects disguised files).
* Size is enforced while reading; nothing larger than the limit is held in memory.
* Stored names are generated by the server — client filenames are never used for storage.
* SVG and other scriptable formats are not accepted.
"""

import hashlib
import uuid
from dataclasses import dataclass
from pathlib import PurePath

from fastapi import UploadFile

from app.core.errors import PayloadTooLargeError, UnsupportedMediaTypeError, ValidationAppError

MB = 1024 * 1024
MAX_IMAGE_BYTES = 5 * MB
MAX_DOCUMENT_BYTES = 10 * MB


@dataclass(frozen=True)
class FileKind:
    mime: str
    extension: str
    allowed_extensions: frozenset[str]


JPEG = FileKind("image/jpeg", "jpg", frozenset({"jpg", "jpeg"}))
PNG = FileKind("image/png", "png", frozenset({"png"}))
WEBP = FileKind("image/webp", "webp", frozenset({"webp"}))
PDF = FileKind("application/pdf", "pdf", frozenset({"pdf"}))

IMAGE_KINDS = frozenset({JPEG, PNG, WEBP})
DOCUMENT_KINDS = frozenset({JPEG, PNG, WEBP, PDF})

# PDF features that can execute or smuggle content; never needed in business documents.
_PDF_ACTIVE_CONTENT = (b"/JavaScript", b"/JS", b"/Launch", b"/EmbeddedFile", b"/OpenAction")


@dataclass(frozen=True)
class ValidatedFile:
    data: bytes
    kind: FileKind
    sha256: str

    @property
    def size(self) -> int:
        return len(self.data)

    def storage_name(self) -> str:
        return f"{uuid.uuid4().hex}.{self.kind.extension}"


def detect_kind(data: bytes) -> FileKind | None:
    if data.startswith(b"\xff\xd8\xff"):
        return JPEG
    if data.startswith(b"\x89PNG\r\n\x1a\n"):
        return PNG
    if len(data) >= 12 and data[:4] == b"RIFF" and data[8:12] == b"WEBP":
        return WEBP
    if data.startswith(b"%PDF-"):
        return PDF
    return None


def validate_bytes(
    data: bytes, filename: str | None, *, allowed: frozenset[FileKind], max_bytes: int
) -> ValidatedFile:
    if not data:
        raise ValidationAppError("The file is empty", code="empty_file")
    if len(data) > max_bytes:
        raise PayloadTooLargeError(f"File exceeds the {max_bytes // MB} MB limit")

    kind = detect_kind(data)
    if kind is None or kind not in allowed:
        allowed_names = ", ".join(sorted(k.extension.upper() for k in allowed))
        raise UnsupportedMediaTypeError(f"Unsupported file type. Allowed: {allowed_names}")

    extension = PurePath(filename or "").suffix.lower().lstrip(".")
    if extension not in kind.allowed_extensions:
        raise ValidationAppError(
            "File extension does not match its contents", code="extension_mismatch"
        )

    if kind is PDF and any(marker in data for marker in _PDF_ACTIVE_CONTENT):
        raise UnsupportedMediaTypeError(
            "PDFs with scripts, actions or embedded files are not accepted"
        )

    return ValidatedFile(data=data, kind=kind, sha256=hashlib.sha256(data).hexdigest())


async def read_upload(
    upload: UploadFile, *, allowed: frozenset[FileKind], max_bytes: int
) -> ValidatedFile:
    data = await upload.read(max_bytes + 1)
    await upload.close()
    return validate_bytes(data, upload.filename, allowed=allowed, max_bytes=max_bytes)
